[0m05:44:43.551482 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256559E7C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025655BD9CA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256559E6C90>]}


============================== 05:44:43.581130 | 239eab75-1a8a-460b-bfa8-7effc0017601 ==============================
[0m05:44:43.581130 [info ] [MainThread]: Running with dbt=1.9.4
[0m05:44:43.581130 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Dipesh.Gandhi\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init dbtwithsnowflake', 'send_anonymous_usage_stats': 'True'}
[0m05:44:43.865477 [debug] [MainThread]: Starter project path: C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\include\starter_project
[0m05:44:43.931052 [info ] [MainThread]: 
Your new dbt project "dbtwithsnowflake" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m05:44:43.931052 [info ] [MainThread]: Setting up your profile.
[0m05:45:51.363211 [error] [MainThread]: Encountered an error:

[0m05:45:51.447183 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dipesh.Gandhi\Desktop\Explore tools\DBT\DBT-Snowflake\python312-venv\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m05:45:51.451258 [debug] [MainThread]: Command `dbt init` failed at 05:45:51.451258 after 68.10 seconds
[0m05:45:51.451258 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000256552FD550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002566EB91A00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002566DE89550>]}
[0m05:45:51.453279 [debug] [MainThread]: Flushing usage events
[0m05:45:52.668865 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:35:48.435786 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020DB2953110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020DB2FA7110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020DB2FA71A0>]}


============================== 06:35:48.521557 | 8212aa2d-0498-4fa6-b30c-a3a0e8b3ecbe ==============================
[0m06:35:48.521557 [info ] [MainThread]: Running with dbt=1.9.4
[0m06:35:48.525589 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Dipesh.Gandhi\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbtwithsnowflake', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m06:35:49.530881 [info ] [MainThread]: A project called dbtwithsnowflake already exists here.
[0m06:35:49.549878 [debug] [MainThread]: Command `dbt init` succeeded at 06:35:49.547864 after 1.98 seconds
[0m06:35:49.549878 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020DB3497950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020DB34D1CA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020DB0352B70>]}
[0m06:35:49.549878 [debug] [MainThread]: Flushing usage events
[0m06:35:50.753972 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:39:32.545369 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000284A46FE060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000284A2C14500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000284A4F5A3C0>]}


============================== 06:39:32.561354 | 709bc99a-fd10-460d-a466-3312ff53c52b ==============================
[0m06:39:32.561354 [info ] [MainThread]: Running with dbt=1.9.4
[0m06:39:32.561354 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Dipesh.Gandhi\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug --config-dir', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:39:32.593025 [info ] [MainThread]: To view your profiles.yml file, run:

start C:\Users\Dipesh.Gandhi\.dbt
[0m06:39:32.593025 [debug] [MainThread]: Command `dbt debug` succeeded at 06:39:32.593025 after 0.23 seconds
[0m06:39:32.593025 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000284A2C14500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000284A5297AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000284A52C0AD0>]}
[0m06:39:32.593025 [debug] [MainThread]: Flushing usage events
[0m06:39:33.685466 [debug] [MainThread]: An error was encountered while trying to flush usage events
